import base64
import pandas as pd
from Detection import brute_map, detection

# --- Build DataFrames ---
df = pd.DataFrame(detection, columns=["ip", "user_agent", "method", "timestamp", "rule"])

formatted_list = []
for ip, data in brute_map.items():
    formatted_list.append({
        "ip": ip,
        "first_timestamp": data[0],
        "count": data[1],
        "last_timestamp": data[2],
        "status_code": data[3],
        "user_agent": data[4]
    })
df1 = pd.DataFrame(formatted_list)

# --- Convert charts to base64 ---
def encode_image(path):
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")

chart_rules    = encode_image("chart_rules.png")
chart_ips      = encode_image("chart_ips.png")
chart_requests = encode_image("chart_requests.png")
chart_timeline = encode_image("chart_timeline.png")

# --- Summary Stats ---
total_alerts    = len(detection)
total_ips       = len(brute_map)
rule_breakdown  = df.groupby("rule").size().to_dict()
top_offender    = df.groupby("ip").size().idxmax()

# --- Build Alerts Table Rows ---
table_rows = ""
for entry in detection:
    ip, agent, method, timestamp, rule = entry
    color = {
        "Nikto": "#fff3cd",
        "SQLI": "#f8d7da",
        "Traversal": "#d1ecf1"
    }.get(rule, "#ffffff")
    table_rows += f"""
    <tr style="background-color:{color}">
        <td>{ip}</td>
        <td>{rule}</td>
        <td>{method}</td>
        <td>{timestamp}</td>
        <td>{agent}</td>
    </tr>"""

# --- Build Rule Breakdown Cards ---
rule_cards = ""
card_colors = {
    "Nikto": "#e74c3c",
    "SQLI": "#e67e22",
    "Traversal": "#8e44ad"
}
for rule, count in rule_breakdown.items():
    color = card_colors.get(rule, "#555")
    rule_cards += f"""
    <div style="background:{color};color:white;padding:20px;border-radius:8px;text-align:center;min-width:150px">
        <div style="font-size:2em;font-weight:bold">{count}</div>
        <div>{rule}</div>
    </div>"""

# --- Full HTML ---
html = f"""<!DOCTYPE html>
<html>
<head>
    <title>Log Analyzer Threat Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; background: #1a1a2e; color: #eee; margin: 0; padding: 20px; }}
        h1 {{ color: #e74c3c; text-align: center; font-size: 2.5em; margin-bottom: 5px; }}
        h2 {{ color: #e74c3c; border-bottom: 1px solid #e74c3c; padding-bottom: 5px; }}
        .subtitle {{ text-align:center; color:#aaa; margin-bottom:30px; }}
        .summary-grid {{ display:flex; gap:20px; flex-wrap:wrap; margin-bottom:30px; }}
        .card {{ background:#16213e; padding:20px; border-radius:8px; text-align:center; flex:1; min-width:150px; border: 1px solid #e74c3c33; }}
        .card .number {{ font-size:2.5em; font-weight:bold; color:#e74c3c; }}
        .card .label {{ color:#aaa; font-size:0.9em; }}
        .rule-cards {{ display:flex; gap:15px; flex-wrap:wrap; margin-bottom:30px; }}
        .charts-grid {{ display:grid; grid-template-columns:1fr 1fr; gap:20px; margin-bottom:30px; }}
        .chart-box {{ background:#16213e; padding:15px; border-radius:8px; border:1px solid #e74c3c33; }}
        .chart-box img {{ width:100%; border-radius:4px; }}
        .chart-box h3 {{ color:#e74c3c; margin:0 0 10px 0; font-size:1em; }}
        table {{ width:100%; border-collapse:collapse; background:#16213e; border-radius:8px; overflow:hidden; }}
        th {{ background:#e74c3c; color:white; padding:12px; text-align:left; }}
        td {{ padding:10px 12px; border-bottom:1px solid #ffffff11; color:#333; }}
        tr:hover td {{ background:#f0f0f0; }}
        .badge {{ padding:3px 8px; border-radius:4px; font-size:0.8em; font-weight:bold; }}
        .badge-nikto {{ background:#e74c3c; color:white; }}
        .badge-sqli {{ background:#e67e22; color:white; }}
        .badge-traversal {{ background:#8e44ad; color:white; }}
    </style>
</head>
<body>
    <h1>🛡️ Threat Detection Report</h1>
    <p class="subtitle">Generated by Log Analyzer | sample_access.log</p>

    <!-- Summary Cards -->
    <h2>Summary</h2>
    <div class="summary-grid">
        <div class="card">
            <div class="number">{total_alerts}</div>
            <div class="label">Total Alerts</div>
        </div>
        <div class="card">
            <div class="number">{total_ips}</div>
            <div class="label">IPs Analyzed</div>
        </div>
        <div class="card">
            <div class="number">{top_offender}</div>
            <div class="label">Top Offender</div>
        </div>
        <div class="card">
            <div class="number">{len(rule_breakdown)}</div>
            <div class="label">Attack Types Detected</div>
        </div>
    </div>

    <!-- Rule Breakdown -->
    <h2>Alerts by Attack Type</h2>
    <div class="rule-cards">
        {rule_cards}
    </div>

    <!-- Charts -->
    <h2>Visual Analysis</h2>
    <div class="charts-grid">
        <div class="chart-box">
            <h3>Alerts by Attack Type</h3>
            <img src="data:image/png;base64,{chart_rules}" />
        </div>
        <div class="chart-box">
            <h3>Alerts by IP Address</h3>
            <img src="data:image/png;base64,{chart_ips}" />
        </div>
        <div class="chart-box">
            <h3>Total Requests per IP</h3>
            <img src="data:image/png;base64,{chart_requests}" />
        </div>
        <div class="chart-box">
            <h3>Alert Timeline</h3>
            <img src="data:image/png;base64,{chart_timeline}" />
        </div>
    </div>

    <!-- Alerts Table -->
    <h2>Full Alert Details</h2>
    <table>
        <tr>
            <th>IP Address</th>
            <th>Attack Type</th>
            <th>Method</th>
            <th>Timestamp</th>
            <th>User Agent</th>
        </tr>
        {table_rows}
    </table>

</body>
</html>"""

# --- Write to file ---
with open("report.html", "w") as f:
    f.write(html)

print("[*] Report saved to report.html — open it in any browser.")